name: Build and deploy

on:
  push:
  pull_request:

jobs:
  hugo-build:
    runs-on: ubuntu-latest
    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/checkout@v4
        
      - name: Build site
        run: hugo --minify
          
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: ${{ vars.SITE_ARTEFACT_NAME }}
          path: public/*

  deploy:
    runs-on: ubuntu-latest
    needs: hugo-build
    if: github.ref == 'refs/heads/master'
    steps:
      
      - name: Fetch artefacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.SITE_ARTEFACT_NAME }}
          path: ./site

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
            
      - name: Upload to site
        run: rsync -avz --delete ./site/ ${{ secrets.SSH_IP}}:${{ secrets.PUBLIC_PATH }}

